### ISSUE TITLE
Deploys to Manual site using CLI failing with 'Error: Not Found'

### ISSUE THREAD

**Issue by mattdsteele** [netlify/actions#12]
Hi! If this would be better in another repo or venue, let me know :)

I'm experimenting with GitHub Actions and would like to try and use it to deploy to a Netlify site, currently configured for manual deploys.

Netlify site: dazzling-cori-fd7552

The site's Actions config is in this repo: https://github.com/mattdsteele/candy-dispenser-site

```yml
      - name: Deploy to Netlify
        uses: 'netlify/actions/cli@master'
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_ACCESS_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE}}
          BUILD_COMMAND: 'pwd && ls -la ${GITHUB_WORKSPACE}/dist/'
        with:
          args: 'deploy -p -d ${GITHUB_WORKSPACE}/dist/'
```

It's failing with an "Error: not found" message:

```
Run netlify/actions/cli@master
/usr/bin/docker run --name bb81a791fb6e8d7f424b95116766bffc6b7f_a6a211 --label 04bb81 --workdir /github/workspace --rm -e NETLIFY_AUTH_TOKEN -e NETLIFY_SITE_ID -e BUILD_COMMAND -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/candy-dispenser-site/candy-dispenser-site":"/github/workspace" 04bb81:a791fb6e8d7f424b95116766bffc6b7f deploy -p -d ${GITHUB_WORKSPACE}/dist/
grep: /github/home/ignore: No such file or directory
 ›   Error: Not Found
##[error]Docker run failed with exit code 2
```

Full details here: https://github.com/mattdsteele/candy-dispenser-site/commit/637e33cf2621d863356f7c690297e710253163c4/checks

I've tried several different flags like `--dir=./dist` but can't seem to change the error message.

Do I have something misconfigured, or am I misunderstanding how to use the CLI Action?
