### ISSUE TITLE
Unexpected input args

### ISSUE THREAD

**Issue by Sceat** [netlify/actions#32]
When using the cli i get an error
```
##[warning]Unexpected input 'args', valid inputs are ['']
Run netlify/actions/cli@master
  with:
    args: deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --message "Publishing app" --prod
  env:
    NETLIFY_SITE_ID: ***
    NETLIFY_AUTH_TOKEN: ***
```

**Comment by lewis-geek** [comment]
I have the same issue, my workflow is working fine, I have no idea how to fix this warning.

**Comment by Sceat** [comment]
@lewis-geek in the mean time i just use the base cli

```yml
- name: publish to netlify
  run: npx netlify-cli deploy --dir dist --site ${{ env.NETLIFY_SITE_ID }} --auth ${{ env.NETLIFY_AUTH_TOKEN }} --message "Publishing app" --prod
  env:
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
```

**Comment by kitop** [comment]
If you set `NETLIFY_SITE_ID` and `NETLIFY_AUTH_TOKEN` in `ENV` there's no need to pass them as flag arguments.
Are you passing them for any particular reason? Would like to know if it warns without `--site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN` part

**Comment by lewis-geek** [comment]
Hi @kitop, I set `deploy --dir=public --prod` in args, but it also causes the same error.

**Comment by praisegeek** [comment]
@lewis-geek Did you try checking the indentations accordingly ?

```yaml
 - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
```
