### ISSUE TITLE
Deployments are "locked" for production context of this site

### ISSUE THREAD

**Issue by vanekj** [netlify/actions#42]
Hello, I would like to use these actions to deploy my website to Netlify, but the script requires user interaction.

<img width="638" alt="Snímek obrazovky 2020-12-08 v 15 06 39" src="https://user-images.githubusercontent.com/18655248/101493959-ff716100-3966-11eb-907f-9f5bd4872ecd.png">

This is my configuration file:
```
name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Run linter 👀
        run: npm run lint

      - name: Build application 🛠
        run: npm run generate

      - name: Deploy to Netlify 🚀
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod

```

The job does not fail, but no deployment happens.

Should I configure something?
I event tried to enable automatic deployments on every push in Netlify, but even with that option it won't work.

Thank you!
