### ISSUE TITLE
Unable to deploy any changes

### ISSUE THREAD

**Issue by afgallo** [netlify/actions#47]
Hi there,

Thanks for providing these libraries for deploying changes to Netlify via Github Actions. I have the below configured in my Github workflow which triggers a Netlify build.

```
  - name: Deploy to Dev
        uses: netlify/actions/build@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          NETLIFY_CMD: npm run build
          NETLIFY_DIR: build/
        if: github.ref == 'refs/heads/develop'
```

Below is a screenshot of my project in Netlify:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/9999415/114644087-34793000-9d1a-11eb-840e-b36e72417f50.png">

Even though everything ***seems*** to succeed, I can se ***no*** changes on my websites.

What am I doing wrong?
