### ISSUE TITLE
'npm run build' results in Command failed with ENOENT: npm run build

### ISSUE THREAD

**Issue by NiketanG** [netlify/actions#57]
Using the action to build and then deploy a Next.js Project to Netlify from Github CI/CD. The Config is as follows:

```
      - name: 🧰 Install dependencies for Next.js Build
        run: npm install
        
      - name: 📦 Run Next.js build to generate the static files
        run: npm run build

      - name: 🚀 Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: build


```

This uses the [netlify-plugin-nextjs](https://github.com/netlify/netlify-plugin-nextjs#readme). Which fails to build the project (execute `npm run build`) with the following error:

![Screenshot from 2022-02-23 01-43-51](https://user-images.githubusercontent.com/22788998/155211663-6509e327-25d1-4806-9dff-d48d4f23cfae.png)
