### ISSUE TITLE
🎉 Updated CLI action for everyone

### ISSUE THREAD

**Issue by South-Paw** [netlify/actions#66]
👋

I got a bit sick of the [`netlify/actions/cli`](https://github.com/netlify/actions/tree/master/cli) consuming an extra 30-50s of runner time on GitHub actions due to it using a Docker layer and requiring that to be built on every run - which by my estimate was resulting in an average deploy time of ~1m 30s when it was used in a workflow.

I made [`South-Paw/action-netlify-cli`](https://github.com/South-Paw/action-netlify-cli) a few months back and just figured I should probably share it here too so others can find it and save themselves some runner minutes as well. It usually takes about 30 seconds to run and doesn't have a Docker layer 👍

I've also tried to improve the documentation in the README and ensure the action outputs are consistent and expected.

I hope that by sharing this here, other developers who were looking for an alternative are able to find it 😄

**Comment by sneko** [comment]
I was using this action for some time until a breaking change where I saw I was not able to specify the version.

I just threw away Netlify action because a simple `npx` usage would work:
```
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy ...
```

Note you could also add it as a dependency and create a custom script to do something like `npm run my-custom-script` (instead of using `npx`).

Hope it helps 👍
