### ISSUE TITLE
Deprecated usage of `set-output`

### ISSUE THREAD

**Issue by raffomania** [netlify/actions#69]
Running an upload to my page like this:
```
            - name: Publish to Netlify Preview
              uses: netlify/actions/cli@master
              with:
                  args: deploy --dir=export/web/Web
              env:
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
```
Results in the following warnings:
```
 Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
There's already a PR open to fix this: https://github.com/netlify/actions/pull/65
